# Generated by Django 3.2.11 on 2022-11-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/portal/default-user.png', upload_to='profile'),
        ),
    ]
